CREATE TABLE `cluster` (
  `id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `status` varchar(255) DEFAULT 'Active',
  `public` BOOLEAN NOT NULL DEFAULT false,
  `image` text DEFAULT NULL,
  `monitoring_password` text NOT NULL,
  `provider` varchar(255) DEFAULT 'Generic',
  `ssh_key_id` char(36) NOT NULL,
  `content` JSON,
  `owner_id` char(36) DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `cluster_status_index` (`status`) USING HASH,
  KEY `cluster_provider_index` (`provider`) USING HASH,
  KEY `cluster_created_at_index` (`created_at`) USING BTREE,
  KEY `cluster_updated_at_index` (`updated_at`) USING BTREE
);

CREATE TABLE `ssh_key` (
  `name` VARCHAR(255)  NOT NULL PRIMARY KEY,
  `public_key` text NOT NULL,
  `private_key` text NOT NULL,
  `owner` VARCHAR(255)  NOT NULL DEFAULT "",
  `modified_by` VARCHAR(255)  NOT NULL DEFAULT "",
  `creation` BIGINT NOT NULL DEFAULT 0,
  `modified` BIGINT NOT NULL DEFAULT 0,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  KEY `ssh_key_creation_index` (`creation`) USING BTREE,
  KEY `ssh_key_modified_index` (`modified`) USING BTREE,
  KEY `ssh_key_deleted_index` (`deleted`) USING BTREE,
  FULLTEXT KEY `ssh_key_text_search_index` (`name`)
);

CREATE TABLE `user` (
  `name` VARCHAR(255)  NOT NULL UNIQUE,
  `email` VARCHAR(255)  NOT NULL,
  `username` VARCHAR(255)  NOT NULL,
  `password` TEXT NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `first_name` VARCHAR(255)  NOT NULL,
  `middle_name` VARCHAR(255) ,
  `last_name` VARCHAR(255) ,
  `full_name` VARCHAR(255)  NOT NULL,
  `language` VARCHAR(255)  NOT NULL DEFAULT "English",
  `time_zone` VARCHAR(255)  NOT NULL DEFAULT "Europe/Istanbul",
  `send_welcome_email` BOOLEAN NOT NULL DEFAULT false,
  `unsubscribed` BOOLEAN NOT NULL DEFAULT true,
  `user_image` TEXT,
  `gender` VARCHAR(255) ,
  `birth_date` BIGINT,
  `phone` VARCHAR(255) ,
  `location` VARCHAR(255) ,
  `bio` TEXT,
  `mobile_no` VARCHAR(255) ,
  `banner_image` TEXT,
  `new_password` TEXT,
  `logout_all_sessions` BOOLEAN NOT NULL DEFAULT false,
  `reset_password_key` VARCHAR(255) ,
  `last_reset_password_key_generated_on` BIGINT,
  `last_password_reset_date` BIGINT,
  `email_signature` TEXT,
  `simultaneous_sessions` BOOLEAN NOT NULL DEFAULT true,
  `last_ip` VARCHAR(255) ,
  `last_login` VARCHAR(255) ,
  `login_after` INT(11),
  `login_before` INT(11),
  `user_type` VARCHAR(255) ,
  `last_active` BIGINT,
  `bypass_restrict_ip_check_if_2fa_enabled` BOOLEAN NOT NULL DEFAULT false,
  `last_known_versions` TEXT,
  `api_key` VARCHAR(255)  UNIQUE,
  `api_secret` VARCHAR(255) UNIQUE,
  `owner` VARCHAR(255)  NOT NULL DEFAULT "",
  `modified_by` VARCHAR(255)  NOT NULL DEFAULT "",
  `creation` BIGINT NOT NULL DEFAULT 0,
  `modified` BIGINT NOT NULL DEFAULT 0,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`name`),
  KEY `user_creation_index` (`creation`) USING BTREE,
  KEY `user_modified_index` (`modified`) USING BTREE,
  KEY `user_deleted_index` (`deleted`) USING BTREE,
  FULLTEXT KEY `user_text_search_index` (`name`)
);

CREATE TABLE `auth_token` (
  `name` VARCHAR(255)  NOT NULL UNIQUE,
  `access_token` VARCHAR(255) DEFAULT '' NOT NULL,
  `refresh_token` VARCHAR(255) DEFAULT '' NOT NULL,
  `issued_time` BIGINT DEFAULT 0 NOT NULL,
  `expire_time` BIGINT DEFAULT 0 NOT NULL,
  `creation` BIGINT DEFAULT 0 NOT NULL,
  `modified` BIGINT DEFAULT 0 NOT NULL,
  `deleted` BIGINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`name`)
);
CREATE UNIQUE INDEX `access_token_idx` ON `auth_token` (`access_token`);
CREATE UNIQUE INDEX `refresh_token_idx` ON `auth_token` (`refresh_token`);

CREATE TABLE `virtual_machine` (
  `id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `status` varchar(255) DEFAULT 'Pending',
  `provider` varchar(255) DEFAULT 'Generic',
  `credentials` longtext DEFAULT NULL CHECK (json_valid(`credentials`)),
  `idx` int(11) DEFAULT 0,
  `platform` text NOT NULL,
  `cluster_id` char(36) NOT NULL,
  `machine_image` text DEFAULT NULL,
  `machine_type` text DEFAULT NULL,
  `private_ip_address` text DEFAULT NULL,
  `public_ip_address` text DEFAULT NULL,
  `public_dns_name` text DEFAULT NULL,
  `private_dns_name` text DEFAULT NULL,
  `disk_size` int(11) DEFAULT 0,
  `volumes` char(36) DEFAULT NULL,
  `virtual_machine_image` char(36) DEFAULT NULL,
  `termination_protection` int(11) DEFAULT NULL,
  `ram` bigint(20) DEFAULT 0,
  `vcpu` int(11) DEFAULT 0,
  `instance_id` text DEFAULT NULL,
  `series` varchar(255) DEFAULT 'WebServer',
  `extra` longtext DEFAULT NULL CHECK (json_valid(`extra`)),
  `owner_id` char(36) DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `virtual_machine_status_index` (`status`) USING HASH,
  KEY `virtual_machine_provider_index` (`provider`) USING HASH,
  KEY `virtual_machine_series_index` (`series`) USING HASH,
  KEY `virtual_machine_created_at_index` (`created_at`) USING BTREE,
  KEY `virtual_machine_updated_at_index` (`updated_at`) USING BTREE
);

CREATE TABLE `virtual_machine_volume` (
  `id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `namespace` varchar(255) DEFAULT 'hc:virtual_machine_volume',
  `volume_id` text DEFAULT NULL,
  `volume_type` text DEFAULT NULL,
  `size` int(11) DEFAULT 0,
  `iops` int(11) DEFAULT 0,
  `throughput` int(11) DEFAULT 0,
  `owner_id` char(36) DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `virtual_machine_volume_created_at_index` (`created_at`) USING BTREE,
  KEY `virtual_machine_volume_updated_at_index` (`updated_at`) USING BTREE
);
