//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auth_token")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub access_token: String,
    #[sea_orm(unique)]
    pub refresh_token: String,
    pub issued_time: i64,
    pub expire_time: i64,
    pub creation: i64,
    pub modified: i64,
    pub deleted: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
