//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub name: String,
    pub email: String,
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    pub enabled: i8,
    pub first_name: String,
    pub middle_name: Option<String>,
    pub last_name: Option<String>,
    pub full_name: String,
    pub language: String,
    pub time_zone: String,
    pub send_welcome_email: i8,
    pub unsubscribed: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_image: Option<String>,
    pub gender: Option<String>,
    pub birth_date: Option<i64>,
    pub phone: Option<String>,
    pub location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    pub mobile_no: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub banner_image: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub new_password: Option<String>,
    pub logout_all_sessions: i8,
    pub reset_password_key: Option<String>,
    pub last_reset_password_key_generated_on: Option<i64>,
    pub last_password_reset_date: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_signature: Option<String>,
    pub simultaneous_sessions: i8,
    pub last_ip: Option<String>,
    pub last_login: Option<String>,
    pub login_after: Option<i32>,
    pub login_before: Option<i32>,
    pub user_type: Option<String>,
    pub last_active: Option<i64>,
    pub bypass_restrict_ip_check_if_2fa_enabled: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_known_versions: Option<String>,
    #[sea_orm(unique)]
    pub api_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub api_secret: Option<String>,
    pub owner: String,
    pub modified_by: String,
    pub creation: i64,
    pub modified: i64,
    pub deleted: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
